name: website_river_auth
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  jaspr: ^0.21.2
  jaspr_riverpod: ^0.4.0
  jaspr_router: ^0.7.3
  jaspr_auth_test_client:
    path: ../jaspr_auth_test_client
  serverpod_auth_client: 2.9.1
  universal_web: ^1.1.1


dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.2.1
  jaspr_builder: ^0.21.2
  jaspr_lints: ^0.5.1
  lints: ^6.0.0

jaspr:
  mode: client

